### ISSUE TITLE
Difference between `street_number` and `house_number`

### ISSUE THREAD

**Issue by maxlang** [OpenCageData/address-formatting#44]
I was curious why `street_number` isn't aliased to `house_number`.

My current guess, based on [this relation](https://www.openstreetmap.org/relation/976696) from OpenStreetMap is that `street_number` relates to the number specified for a whole section of street (eg "This is the 500 block on 18th st.") whereas `house_number` relates to a specific house address (eg "This is 531 18th st.")

Given that the configured components is used as a negative list for the place `name` (as mentioned here https://github.com/OpenCageData/address-formatting/issues/9#issuecomment-68608440), it makes sense that `street_number` shouldn't be included in the place name and shouldn't be included as the `house_number`, so it's just swallowed.

However, I don't see `street_number` in any of the test cases so I don't know if this is the correct/expected behavior.

Anyway, just wanted to add that I really appreciate what you guys are doing. Thanks!

**Comment by freyfogle** [comment]
Hi @maxlang 

first up, thanks for the kind words. 

I am not aware that `street_number` is a common tag in OSM. 
Happy to look more deeply if you can find other examples. 

In many parts of the world roads have numbers rather than (or often in addition to) names. I would assume this was an attempt to tag the number of the road. 

Please do submit any examples or test cases where you think we can improve. The world is a big, chaotic place. There is lots to do.

**Comment by maxlang** [comment]
Thanks for the fast response!

I should specify I was referring to `street_number` here: https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml#L4

I'll definitely submit something if I encounter it.

**Comment by mtmail** [comment]
Looks like I wrote that line. We work with multiple geocoders (https://geocoder.opencagedata.com/credits) and DataScienceToolkit (their website is down?) uses `street_number` in their result response schema. It should've been an alias and I'll update the `components.yaml` file. Thanks!

**Comment by maxlang** [comment]
Sweet, that explains it.

You guys work fast!
